# Generated by Django 3.1.4 on 2021-10-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vm_tenant', '0002_socialuser_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialuser',
            old_name='user_id',
            new_name='id',
        ),
    ]
